import type { Metadata } from "next";
import { K2D, Montserrat } from "next/font/google";
import { getMessages } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";
import { Providers } from "@/modules/common/providers/Providers";
import "./globals.css";
import "easymde/dist/easymde.min.css";

type Params = Promise<{ locale: string }>;

const MontserratFont = Montserrat({
  subsets: ["latin"],
  weight: ["500", "700", "900"],
  variable: "--font-monserrat",
});

const K2DFont = K2D({
  subsets: ["latin"],
  weight: ["500", "700", "800"],
  variable: "--font-k2d",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Params;
}>) {
  const locale = (await params).locale;

  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body
        className={`${K2DFont.variable} ${MontserratFont.variable} antialiased font-monserrat w-screen overflow-x-hidden`}
      >
        <NextIntlClientProvider messages={messages}>
          <Providers>{children}</Providers>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
