import type { Metadata } from "next";
import "./globals.css";
import { K2D, Montserrat } from "next/font/google";
import { getMessages } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";

type Params = Promise<{ locale: string }>;

export const mainFont = Montserrat({
  subsets: ["latin"],
  weight: ["500", "700", "900"],
  variable: "--font-monserrat",
});

export const titleFont = K2D({
  subsets: ["latin"],
  weight: ["500", "700", "800"],
  variable: "--font-k2d",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Params;
}>) {
  const locale = (await params).locale;

  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body
        className={`${mainFont.variable} ${mainFont.variable} antialiased font-monserrat`}
      >
        <NextIntlClientProvider messages={messages}>
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
